import Foundation

/// Supported languages for Whisper speech recognition
///
/// Whisper supports 100 languages for transcription and can translate any of them to English.
/// Order matches the official Whisper language token order for consistency.
public enum Language: String, CaseIterable, Sendable {
  case english = "en"
  case chinese = "zh"
  case german = "de"
  case spanish = "es"
  case russian = "ru"
  case korean = "ko"
  case french = "fr"
  case japanese = "ja"
  case portuguese = "pt"
  case turkish = "tr"
  case polish = "pl"
  case catalan = "ca"
  case dutch = "nl"
  case arabic = "ar"
  case swedish = "sv"
  case italian = "it"
  case indonesian = "id"
  case hindi = "hi"
  case finnish = "fi"
  case vietnamese = "vi"
  case hebrew = "he"
  case ukrainian = "uk"
  case greek = "el"
  case malay = "ms"
  case czech = "cs"
  case romanian = "ro"
  case danish = "da"
  case hungarian = "hu"
  case tamil = "ta"
  case norwegian = "no"
  case thai = "th"
  case urdu = "ur"
  case croatian = "hr"
  case bulgarian = "bg"
  case lithuanian = "lt"
  case latin = "la"
  case maori = "mi"
  case malayalam = "ml"
  case welsh = "cy"
  case slovak = "sk"
  case telugu = "te"
  case persian = "fa"
  case latvian = "lv"
  case bengali = "bn"
  case serbian = "sr"
  case azerbaijani = "az"
  case slovenian = "sl"
  case kannada = "kn"
  case estonian = "et"
  case macedonian = "mk"
  case breton = "br"
  case basque = "eu"
  case icelandic = "is"
  case armenian = "hy"
  case nepali = "ne"
  case mongolian = "mn"
  case bosnian = "bs"
  case kazakh = "kk"
  case albanian = "sq"
  case swahili = "sw"
  case galician = "gl"
  case marathi = "mr"
  case punjabi = "pa"
  case sinhala = "si"
  case khmer = "km"
  case shona = "sn"
  case yoruba = "yo"
  case somali = "so"
  case afrikaans = "af"
  case occitan = "oc"
  case georgian = "ka"
  case belarusian = "be"
  case tajik = "tg"
  case sindhi = "sd"
  case gujarati = "gu"
  case amharic = "am"
  case yiddish = "yi"
  case lao = "lo"
  case uzbek = "uz"
  case faroese = "fo"
  case haitianCreole = "ht"
  case pashto = "ps"
  case turkmen = "tk"
  case nynorsk = "nn"
  case maltese = "mt"
  case sanskrit = "sa"
  case luxembourgish = "lb"
  case myanmar = "my"
  case tibetan = "bo"
  case tagalog = "tl"
  case malagasy = "mg"
  case assamese = "as"
  case tatar = "tt"
  case hawaiian = "haw"
  case lingala = "ln"
  case hausa = "ha"
  case bashkir = "ba"
  case javanese = "jw"
  case sundanese = "su"
  case cantonese = "yue"

  /// Human-readable language name in English
  public var displayName: String {
    switch self {
      case .english: "English"
      case .chinese: "Chinese"
      case .german: "German"
      case .spanish: "Spanish"
      case .russian: "Russian"
      case .korean: "Korean"
      case .french: "French"
      case .japanese: "Japanese"
      case .portuguese: "Portuguese"
      case .turkish: "Turkish"
      case .polish: "Polish"
      case .catalan: "Catalan"
      case .dutch: "Dutch"
      case .arabic: "Arabic"
      case .swedish: "Swedish"
      case .italian: "Italian"
      case .indonesian: "Indonesian"
      case .hindi: "Hindi"
      case .finnish: "Finnish"
      case .vietnamese: "Vietnamese"
      case .hebrew: "Hebrew"
      case .ukrainian: "Ukrainian"
      case .greek: "Greek"
      case .malay: "Malay"
      case .czech: "Czech"
      case .romanian: "Romanian"
      case .danish: "Danish"
      case .hungarian: "Hungarian"
      case .tamil: "Tamil"
      case .norwegian: "Norwegian"
      case .thai: "Thai"
      case .urdu: "Urdu"
      case .croatian: "Croatian"
      case .bulgarian: "Bulgarian"
      case .lithuanian: "Lithuanian"
      case .latin: "Latin"
      case .maori: "Maori"
      case .malayalam: "Malayalam"
      case .welsh: "Welsh"
      case .slovak: "Slovak"
      case .telugu: "Telugu"
      case .persian: "Persian"
      case .latvian: "Latvian"
      case .bengali: "Bengali"
      case .serbian: "Serbian"
      case .azerbaijani: "Azerbaijani"
      case .slovenian: "Slovenian"
      case .kannada: "Kannada"
      case .estonian: "Estonian"
      case .macedonian: "Macedonian"
      case .breton: "Breton"
      case .basque: "Basque"
      case .icelandic: "Icelandic"
      case .armenian: "Armenian"
      case .nepali: "Nepali"
      case .mongolian: "Mongolian"
      case .bosnian: "Bosnian"
      case .kazakh: "Kazakh"
      case .albanian: "Albanian"
      case .swahili: "Swahili"
      case .galician: "Galician"
      case .marathi: "Marathi"
      case .punjabi: "Punjabi"
      case .sinhala: "Sinhala"
      case .khmer: "Khmer"
      case .shona: "Shona"
      case .yoruba: "Yoruba"
      case .somali: "Somali"
      case .afrikaans: "Afrikaans"
      case .occitan: "Occitan"
      case .georgian: "Georgian"
      case .belarusian: "Belarusian"
      case .tajik: "Tajik"
      case .sindhi: "Sindhi"
      case .gujarati: "Gujarati"
      case .amharic: "Amharic"
      case .yiddish: "Yiddish"
      case .lao: "Lao"
      case .uzbek: "Uzbek"
      case .faroese: "Faroese"
      case .haitianCreole: "Haitian Creole"
      case .pashto: "Pashto"
      case .turkmen: "Turkmen"
      case .nynorsk: "Nynorsk"
      case .maltese: "Maltese"
      case .sanskrit: "Sanskrit"
      case .luxembourgish: "Luxembourgish"
      case .myanmar: "Myanmar"
      case .tibetan: "Tibetan"
      case .tagalog: "Tagalog"
      case .malagasy: "Malagasy"
      case .assamese: "Assamese"
      case .tatar: "Tatar"
      case .hawaiian: "Hawaiian"
      case .lingala: "Lingala"
      case .hausa: "Hausa"
      case .bashkir: "Bashkir"
      case .javanese: "Javanese"
      case .sundanese: "Sundanese"
      case .cantonese: "Cantonese"
    }
  }

  /// Initialize from language code string
  /// - Parameter code: Two-letter ISO 639-1 code (or special codes like "haw")
  /// - Returns: Language if recognized, nil otherwise
  public init?(code: String) {
    self.init(rawValue: code)
  }

  /// The language code (ISO 639-1 or equivalent)
  public var code: String { rawValue }
}
